### ISSUE TITLE
UI thoughts

### ISSUE THREAD

**Issue by waqasbhatti** [johnnygreco/viz-inspect#2]
Let's use this issue to handle UI issues. I made a quick mockup based on your current https://github.com/johnnygreco/udg-zoo. 

![screencapture-localhost-14005-2019-02-28-14_55_14](https://user-images.githubusercontent.com/1868184/53594605-34813a80-3b69-11e9-95c9-b6e24759f5af.png)

The template bits that I used are in:

https://github.com/johnnygreco/viz-inspect/blob/a2ab57ad392b83d31d1ba88996665e848dccdb1f/vizinspect/frontend/templates/index.html#L1      

This is in a separate branch: wbhatti-ui-experiments so it doesn't interfere with what you're doing on the master branch. Feel free to grab whatever you need from there.

**Comment by waqasbhatti** [comment]
Continuing work in the wbhatti-ui-experiments branch, now close to replicating your existing udg-zoo project:

![screencapture-localhost-14005-2019-03-07-23_35_39](https://user-images.githubusercontent.com/1868184/54007925-52830800-4132-11e9-88d1-41293838e5a6.png)

TBD:

- [ ] finish up and test the load-object, save-object handlers
- [ ] hook up JS for backend requests
- [ ] decipher hscMap URL and hook that up
- [ ] figure how to serialize simultaneous work by several people on a single object
- [ ] possibly move from the current catalog.csv + comments.csv model to SQLite for everything

**Comment by johnnygreco** [comment]
🤯
